version: '2'
services:
  bayikodris-app:
    image: bayikodris
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bayikodris-postgresql:5432/BayiKodris
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  bayikodris-postgresql:
    extends:
      file: postgresql.yml
      service: bayikodris-postgresql
